2020-12-09 14:02:09,083 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:02:09,759 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:02:09,825 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:02:09,839 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:02:10,174 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:02:10,187 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:04:36,411 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:04:37,014 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:04:37,030 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:04:37,036 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:04:37,053 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:04:37,077 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:04:37,717 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:04:37,739 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:14:30,270 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:14:30,874 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:14:30,892 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:14:30,904 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:14:31,226 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:14:31,250 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:14:57,800 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:14:58,409 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:14:58,427 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:14:58,434 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:14:58,442 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:14:58,464 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:14:58,845 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:14:58,875 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:15:44,273 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:15:44,877 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:15:44,892 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:15:44,900 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:15:44,906 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:15:45,685 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:16:40,096 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:16:40,772 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:16:40,803 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:16:40,816 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:16:40,847 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:16:41,088 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:16:41,104 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:17:39,949 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:17:40,554 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:17:40,569 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:17:40,575 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:17:40,945 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:17:41,012 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:18:45,640 - root - ERROR - task_controler.py:384 - get no user by code 222222222
2020-12-09 14:22:51,351 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:22:52,030 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:22:52,060 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:22:52,072 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:22:52,096 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:22:52,126 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:22:52,163 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:22:52,239 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:24:02,006 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:24:02,718 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:24:02,748 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:24:02,760 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:24:03,544 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:24:03,578 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:24:56,102 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:24:56,784 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:24:56,815 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:24:56,826 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:24:57,621 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:25:10,603 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:25:11,337 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:25:11,368 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:25:11,381 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:25:11,775 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:25:11,890 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:35:24,656 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:35:25,340 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:35:25,368 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:35:25,384 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:35:26,377 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:35:26,528 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:35:30,570 - root - WARNING - gateway_server.py:106 - equipment (192.168.0.201, 4370) is offline
2020-12-09 14:38:13,433 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:38:14,192 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:38:14,232 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:38:14,244 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:38:14,291 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:38:14,318 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:38:14,605 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:38:14,651 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:39:23,414 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:39:24,085 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:39:24,114 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:39:24,125 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:39:24,137 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:39:24,432 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:39:24,505 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:39:36,459 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:39:37,204 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:39:37,241 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:39:37,257 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:39:37,307 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:39:37,317 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:39:38,005 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:39:38,077 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:40:02,437 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:40:03,182 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:40:03,231 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:40:03,254 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:40:07,967 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:40:08,638 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:40:08,665 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:40:08,676 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:40:08,696 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:40:08,735 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:40:09,584 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:40:24,898 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:40:25,613 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:40:25,646 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:40:25,665 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:40:26,247 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:40:26,292 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:41:39,140 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:41:40,087 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:41:40,136 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:41:40,164 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:42:40,805 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:42:41,478 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:42:41,504 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:42:41,514 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:42:41,560 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:42:41,589 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:42:42,147 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:42:42,218 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:46:08,650 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:46:09,388 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:46:09,437 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:46:09,454 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:46:09,466 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:46:09,510 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:46:10,307 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:46:10,327 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:46:33,490 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:46:34,173 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:46:34,383 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:46:34,409 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:46:34,421 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:46:34,439 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:46:34,658 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:46:34,700 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:48:52,720 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:48:53,459 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:48:53,492 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:48:53,507 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:48:54,130 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 14:48:54,206 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 14:50:08,014 - root - INFO - main.py:60 - START SERVER
2020-12-09 14:50:08,726 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 14:50:08,765 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 14:50:08,784 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 14:50:09,656 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 15:07:04,108 - root - INFO - main.py:60 - START SERVER
2020-12-09 15:07:04,866 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-09 15:07:04,948 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 15:07:04,974 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:05,023 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 15:07:05,044 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-09 15:07:05,083 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-09 15:07:05,129 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:05,249 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-09 15:07:05,316 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-09 15:07:06,216 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:07,221 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:08,218 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:09,211 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:10,169 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:11,258 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:12,280 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:13,169 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:14,196 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:15,208 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:16,221 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:17,217 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:18,195 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:19,222 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:20,161 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:21,177 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:22,218 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:23,192 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:24,212 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:25,263 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:26,247 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
2020-12-09 15:07:27,240 - root - WARNING - Object2.py:854 - (192.168.0.201, 4370)--GetDeviceData() get no registerd user
