2020-12-18 15:49:36,269 - root - INFO - main.py:63 - START SERVER
2020-12-18 15:49:37,484 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-18 15:49:37,513 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-18 15:49:37,525 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-18 15:49:37,535 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-18 15:49:38,286 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-18 15:49:38,380 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-18 15:57:01,410 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 15:59:49,619 - root - ERROR - Object2.py:637 - index out of range
2020-12-18 16:05:52,174 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 16:11:02,151 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 16:21:22,229 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 16:25:41,200 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 16:27:51,695 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 16:28:27,808 - root - ERROR - Object2.py:637 - index out of range
