2021-01-28 15:10:51,395 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:10:56,399 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:11:01,402 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:11:06,405 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:11:11,407 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:11:16,410 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:11:21,412 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:11:26,415 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:11:31,422 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:11:36,425 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:11:41,430 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:11:46,432 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:11:51,443 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:11:56,452 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:12:01,458 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:12:06,461 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:12:11,464 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:12:16,466 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:12:21,469 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:12:26,472 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:12:31,475 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:12:36,478 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:12:41,480 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:12:46,484 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:12:51,490 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:12:56,497 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:13:01,502 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:13:06,503 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:13:11,509 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:13:16,510 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:13:21,512 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:13:26,514 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:13:31,517 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:13:36,519 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:13:41,522 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:13:46,525 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:13:51,528 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:13:56,531 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:14:01,535 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:14:06,537 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:14:11,539 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:14:16,542 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:14:21,545 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:14:26,548 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:14:31,550 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:14:36,553 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:14:41,555 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:14:46,558 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:14:51,563 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:14:56,565 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:15:01,572 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:15:06,574 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:15:11,577 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:15:16,589 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:15:21,590 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:15:26,592 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:15:31,594 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:15:36,598 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:15:41,600 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:15:46,604 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:15:51,607 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:15:56,610 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:16:01,613 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:16:06,616 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:16:11,619 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:16:16,622 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:16:21,625 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:16:26,628 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:16:31,631 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:16:36,634 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:16:41,637 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:16:46,640 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
2021-01-28 15:16:51,642 - root - ERROR - channel_machine_test.py:102 - CM_R2000RH(10.0.218.46, 59225) exception: 'ChannelMachineR2000FH' object has no attribute 'data_buff'
