2020-12-18 15:49:36,269 - root - INFO - main.py:63 - START SERVER
2020-12-18 15:49:37,484 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-18 15:49:37,513 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-18 15:49:37,525 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-18 15:49:37,535 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-18 15:49:38,286 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-18 15:49:38,380 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-18 15:57:01,410 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 15:59:49,619 - root - ERROR - Object2.py:637 - index out of range
2020-12-18 16:05:52,174 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 16:11:02,151 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 16:21:22,229 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 16:25:41,200 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 16:27:51,695 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 16:28:27,808 - root - ERROR - Object2.py:637 - index out of range
2020-12-18 16:42:41,816 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 16:51:41,484 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 16:51:52,737 - root - ERROR - Object2.py:637 - index out of range
2020-12-18 16:58:51,473 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 17:02:18,165 - root - ERROR - Object2.py:637 - index out of range
2020-12-18 17:03:51,784 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 17:11:01,199 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 17:14:51,725 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 17:35:01,835 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 17:45:31,725 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-18 17:50:02,060 - root - ERROR - Object2.py:637 - index out of range
2020-12-18 18:16:44,305 - root - INFO - main.py:63 - START SERVER
2020-12-18 18:16:45,033 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-18 18:16:45,063 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-18 18:16:45,074 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-18 18:16:45,084 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-18 18:16:45,104 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-18 18:16:45,932 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-18 18:16:46,003 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-18 18:17:31,235 - root - ERROR - Object2.py:63 - 'int' object has no attribute 'hex'
2020-12-18 18:19:31,230 - root - ERROR - Object2.py:63 - 'int' object has no attribute 'hex'
2020-12-18 18:23:24,276 - root - ERROR - Object2.py:638 - index out of range
2020-12-18 18:28:53,357 - root - INFO - main.py:63 - START SERVER
2020-12-18 18:28:53,983 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-18 18:28:53,996 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-18 18:28:54,005 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-18 18:28:54,021 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-18 18:28:54,042 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-18 18:28:54,071 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-18 18:45:29,239 - root - INFO - main.py:63 - START SERVER
2020-12-18 18:45:29,930 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-18 18:45:29,972 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-18 18:45:29,989 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-18 18:45:30,001 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-18 18:45:30,619 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-18 18:45:30,662 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-18 19:02:44,013 - root - INFO - main.py:63 - START SERVER
2020-12-18 19:02:44,637 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-18 19:02:44,656 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.118', 23))已成功连接。。online
2020-12-18 19:02:44,669 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-18 19:02:44,678 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-18 19:02:44,700 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-18 19:02:44,722 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.118', 23))已成功连接。。online
2020-12-18 19:02:45,026 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-18 19:02:45,080 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
